### PR TITLE
Moves TOC to left nav on docs pages

### PR DESCRIPTION
**Pull request by meiqimichelle**
For #6 .

This PR moves the Hugo auto-generated Table of Contents from the right side of the page (where it was sometimes hidden and inaccessible, depending on screen size), to the left nav (which it is always accessible, either in view or via a hamburger nav button at smaller screen sizes).

In order to make this work, I moved the sub-nav to breadcrumbs, and also fixed a few issues with the way the Hugo templates were being generated. (Fun Hugo quirk: you have to provide separate templates for "section" pages, which are at www.mysite.com/SECTION, versus "single" pages, which is everything under that, such as www.mysite.com/docs/SINGLE; www.mysite.com/docs/spec; etc.)

As a result, there's a new `_index.md` page in the `content/docs` folder so that there's a layout available at `/docs/`, ie:
Screenshot 2020-01-21 15 22 27
`/docs/` was previously redirecting to `/docs/overview` but that was breaking Hugo's ability to auto-generate nav and breadcrumbs. There still might be a way to re-direct this, however, I think this page will come in handy when writing the overview, and so I left it as a stub for now.

### Preview

Documentation pages at larger screen sizes...
Screenshot 2020-01-21 15 09 10

Documentation pages at smaller screen sizes...

TOC collapsed:
Screenshot 2020-01-21 15 12 58

TOC open:
Screenshot 2020-01-21 15 13 09

I plan to improve the layout/typography still (for example, the spacing/indents in the TOC aren't great right now). @ultrasaurus -- are you happy reviewing as-is for starters?

### CODE REVIEW

**Comment by ultrasaurus** [comment]
I really like this direction. The breadcrumbs are a nice solution to multiple navigational elements -- if not too difficult, I think it would be nice to have breadcrumbs be the full width of the header, so page outline gets tucked under the breadcrumbs. 

It may be just that this is work-in-progress (with overview as placeholder), but would want to get this view fixed up to be nicer before merging:

image

By the way, it's on my list (across multiple projects) to figure out how going to /docs/ could automatically redirect to the first page of that section -- let me know if it would be helpful to figure that out sooner rather than later.

**Comment by meiqimichelle** [comment]
@ultrasaurus we're getting there! So far, I've:

- Moved the breadcrumbs and styled them so that we've got a two-layer nav that sticks, and also doesn't block the search box on scroll.
- Toned down the default red throughout the site (still red, just a different red), and copied the gradient red from the bottom of the Veriskope site into the header here because flashy.
- Improved the readability of the nav in general (upping contrast; providing visual indicator that is *not* color for which spot you're at; differentiated nav text from general text via small-caps and spacing)

Screenshot 2020-01-23 17 47 38

Up next: improved styling in TOC, and another pass at link indicators. It's not good that sometimes 'underline' is 'u r here', and sometimes 'underline' is 'i am a link' and sometimes 'underline' is 'u r hovering on a link'.

**Comment by meiqimichelle** [comment]
OK! This is where we're at:
Screenshot 2020-01-23 19 10 42

@ultrasaurus back to you for review. I think this may be good enough for another incremental push. You should in particular review where content lives in our docs section. For example, start at the home page, and click on any of the calls to action there, or the `Documentation` in the main nav, as if you were accessing docs after arriving at the site.

**Comment by meiqimichelle** [comment]
Oh also -- please check to see if those left nav table of contents list items are displaying with circles/discs etc for you, like they were earlier. I updated my version of Hugo which solved some of my display issues, but I don't think it's solved them all. Thank you!

**Comment by ultrasaurus** [comment]
The left nav is cropped for me... were you intentionally showing bullets or is the spacing weird because they aren't supposed to be there?

image

Note: the black line on left is the window behind the web browser.  I included it so you could see how it looks

**Comment by meiqimichelle** [comment]
@ultrasaurus try now?

**Comment by ultrasaurus** [comment]
Looks great!

image

**Pull request merged**
