### PR TITLE
Streamline docs content

### PR DESCRIPTION
**Pull request by meiqimichelle**
This PR moves what was a separate `Protocol References` docs page to the Documentation section home; translates that content to from `.html` to `.md`; re-creates the `Overview` page; and moves the `Chunk Stream Message Format` cheat-sheet to a section on the `Overview` page.

Example:
Screenshot 2020-01-24 18 04 04

### CODE REVIEW

**Comment by meiqimichelle** [comment]
(Sigh. I don't know why this old commit appears in the history here:
`Add sneaky regex + svg link img after headings in docs` )

**Comment by ultrasaurus** [comment]
could you pull master and rebase the branch?  (prolly why old commit appears in the history)

**Comment by ultrasaurus** [comment]
Screen shot looks fab!

**Comment by meiqimichelle** [comment]
Let's try this one more time :) How does it look now?

**Comment by meiqimichelle** [comment]
Aw. Boo. Closing this PR, will make a better-commit-history one in a moment....

**Pull request closed without merging**
